name: build-container
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  results:
    # This job was inspired by https://github.com/orgs/community/discussions/26822#discussioncomment-5122101
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Final Results
    needs: [docker]
    steps:
      - run: exit 1
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}

  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - alpine-latest
          - alpine-3.15.0
          - alpine-3.10
          - alpine-edge
          - debian-11.1
          - debian-10.1
          - debian-10.2
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
        screen:
          - broadway
          - xpra
        include:
          - distro: alpine-latest
            platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          - distro: alpine-3.15.0
            platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          - distro: alpine-3.10
            platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          - distro: alpine-edge
            platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/riscv64, linux/s390x
          - distro: debian-10.1
            platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
            screen: broadway
          - distro: debian-10.1
            platforms: linux/amd64
            screen: xpra
          - distro: debian-10.2
            platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
            screen: broadway
          - distro: debian-10.2
            platforms: linux/amd64
            screen: xpra
          - distro: debian-11.1
            platforms: linux/386, linux/amd64, linux/arm/v7, linux/arm64/v8, linux/mips64le, linux/ppc64le, linux/s390x
            screen: broadway
          - distro: debian-11.1
            platforms: linux/amd64
            screen: xpra
          - distro: ubuntu-16.04
            platforms: linux/386, linux/amd64, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
            screen: broadway
          - distro: ubuntu-18.04
            platforms: linux/386, linux/amd64, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
            screen: broadway
          - distro: ubuntu-18.04
            platforms: linux/amd64
            screen: xpra
          - distro: ubuntu-20.04
            platforms: linux/amd64, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
            screen: broadway
          - distro: ubuntu-20.04
            platforms: linux/amd64
            screen: xpra
          - distro: ubuntu-22.04
            platforms: linux/amd64, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
            screen: broadway
          - distro: ubuntu-22.04
            platforms: linux/amd64
            screen: xpra
        exclude:
          - distro: alpine-3.10
            screen: xpra
          - distro: ubuntu-16.04
            screen: xpra
    steps:
      - id: repository
        run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          platforms: ${{ matrix.platforms }}
          file: ${{ matrix.distro }}_${{ matrix.screen }}/Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: pizzafactory0contorno/${{ steps.repository.outputs.name }}:${{ matrix.distro }}_${{ matrix.screen }}
          cache-from: type=gha
          cache-to: type=gha,mode=max,scope=${{ matrix.distro }}-${{ matrix.screen }}
