name: build-container
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  broadway:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - alpine
          - alpine-edge
          - alpine-3.15.0
          - alpine-3.10 
          - debian-11.1
          - debian-10.1
          - debian-10.2
          - debian-9.11
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
        include:
          - tag: alpine
            dockerfile: Dockerfile.alpine
            platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          - tag: alpine-edge
            dockerfile: Dockerfile.alpine
            platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          - tag: alpine-3.15.0
            dockerfile: Dockerfile.alpine
            platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          - tag: alpine-3.10
            dockerfile: Dockerfile.alpine
            platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          - tag: debian-11.1
            dockerfile: Dockerfile.debian
            platforms: linux/386, linux/amd64, linux/arm/v7, linux/arm64/v8, linux/mips64le, linux/ppc64le, linux/s390x
          - tag: debian-10.1
            dockerfile: Dockerfile.debian
            platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          - tag: debian-10.2
            dockerfile: Dockerfile.debian
            platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          - tag: debian-9.11
            dockerfile: Dockerfile.debian
            platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          - tag: ubuntu-20.04
            dockerfile: Dockerfile.debian
            platforms: linux/amd64, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/riscv64, linux/s390x
          - tag: ubuntu-18.04
            dockerfile: Dockerfile.debian
            platforms: linux/386, linux/amd64, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          - tag: ubuntu-16.04
            extraPlatforms: riscv64
            dockerfile: Dockerfile.debian
            platforms: linux/386, linux/amd64, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build (and push)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platforms }}
          file: ${{ matrix.dockerfile }}_broadway
          build-args: BASE_IMAGE=pizzafactory0contorno/piatto:${{ matrix.tag }}
          push: ${{ github.event_name == 'push' }}
          tags: pizzafactory0contorno/piatto-quadrato:${{ matrix.tag }}
  xpra:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - alpine
          - alpine-edge
          - alpine-3.15.0
          # - alpine-3.10 # as no apk provided.
          - debian-11.1
          - debian-10.1
          - debian-10.2
          - debian-9.11
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
        include:
          - tag: alpine
            dockerfile: Dockerfile.alpine
            platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          - tag: alpine-edge
            dockerfile: Dockerfile.alpine
            platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          - tag: alpine-3.15.0
            dockerfile: Dockerfile.alpine
            platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          # - tag: alpine-3.10
          #   dockerfile: Dockerfile.alpine
          #   platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          - tag: debian-11.1
            dockerfile: Dockerfile.debian
            platforms: linux/386, linux/amd64
          - tag: debian-10.1
            dockerfile: Dockerfile.debian
            platforms: linux/386, linux/amd64
          - tag: debian-10.2
            dockerfile: Dockerfile.debian
            platforms: linux/386, linux/amd64
          - tag: debian-9.11
            dockerfile: Dockerfile.debian
            platforms: linux/386, linux/amd64
          - tag: ubuntu-20.04
            dockerfile: Dockerfile.ubuntu
            platforms: linux/amd64
          - tag: ubuntu-18.04
            dockerfile: Dockerfile.ubuntu
            platforms: linux/386, linux/amd64
          - tag: ubuntu-16.04
            extraPlatforms: riscv64
            dockerfile: Dockerfile.ubuntu
            platforms: linux/386, linux/amd64
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build (and push)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.platforms }}
          file: ${{ matrix.dockerfile }}_xpra
          build-args: BASE_IMAGE=pizzafactory0contorno/piatto:${{ matrix.tag }}
          push: ${{ github.event_name == 'push' }}
          tags: pizzafactory0contorno/piatto-quadrato:${{ matrix.tag }}
